### ISSUE TITLE
Add qtime property to Job struct

### ISSUE THREAD

**Issue by dewski** [zencoder/disque-go#1]
It'd be nice touch to be able to access the time the job was queued into disque. My use case is the message is a JSON payload which may or may not include a timestamp provided by the client. If one isn't provided, I'd fallback to the `qtime` property.

**Comment by skidder** [comment]
I've added a function to get the details of a queued job: `GetJobDetails`.  This will return a struct with the full set of attributes associated with the job, including the time when the job was created.  Good suggestion, and I hope this addresses your use-case.

**Comment by dewski** [comment]
@skidder thanks for the prompt addition. Added one small bit of feedback, but already put to good use :+1:

**Comment by skidder** [comment]
Cool, glad I was able to help.  Thanks for the feedback!
