### ISSUE TITLE
Consider WITHCOUNTERS

### ISSUE THREAD

**Issue by pschultz** [zencoder/disque-go#13]
How do you feel about adding the WITHCOUNTERS options to the GETJOB command and consequently Nacks and AdditionalDeliveries to the Job struct? 

In all of our use cases we inspect those counters to eventually give up on a job. As it is now we always have to do two calls for what could be done in one.

**Comment by skidder** [comment]
Thank you @pschultz , this is a great suggestion. I'll check it out in the next 24 hours along with your pull-requests.

**Comment by skidder** [comment]
@pschultz I've added the `Nacks` and `AdditionalDeliveries` fields to the `Job` struct type and the `WITHCOUNTERS` setting to the job fetch string.  Great suggestion!

**Comment by pschultz** [comment]
Excellent. That improves performance considerably. Thanks.
